{% set version = "6.0.7" %}

package:
  name: nbconvert
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbconvert/nbconvert-{{ version }}.tar.gz
  sha256: cbbc13a86dfbd4d1b5dee106539de0795b4db156c894c2c5dc382062bbc29002

build:
  number: 1

requirements:
  host:
    - python
    - pip
  run:
    - python

outputs:
  - name: nbconvert
    requirements:
      host:
        - python
        - pip
      run:
        - nbconvert-core {{ version }}.*
        # the pin is handled by the run_constrained in core
        - pandoc  # [not aarch64]
    test:
      requires:
        - pip
      commands:
        - python -m pip check

  - name: nbconvert-core
    build:
      script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv
      entry_points:
        - jupyter-nbconvert = nbconvert.nbconvertapp:main

    requirements:
      host:
        - python
        - pip
      run:
        - bleach
        - defusedxml
        - entrypoints >=0.2.2
        - jinja2 >=2.4
        - jupyter_core
        - jupyterlab_pygments
        - mistune >=0.8.1
        - nbclient >=0.5.0,<0.6.0
        - nbformat >=4.4
        - pandocfilters >=1.4.1
        - pygments >=2.4.1
        - python
        - testpath
        - traitlets >=4.2
      run_constrained:
        - pyppeteer ==0.2.2
        - pandoc >=1.12.1
    about:
      description: nbconvert with only core dependencies with limited output options

    test:
      requires:
        - pip
      source_files:
        - nbconvert/tests/files/notebook1.ipynb
      imports:
        - nbconvert
        - nbconvert.exporters
        - nbconvert.filters
        - nbconvert.postprocessors
        - nbconvert.preprocessors
        - nbconvert.resources
        - nbconvert.tests
        - nbconvert.utils
        - nbconvert.writers
      commands:
        - python -m pip check
        - jupyter nbconvert --help
        - jupyter nbconvert nbconvert/tests/files/notebook1.ipynb --to html

  - name: nbconvert-webpdf
    build:
      noarch: python
    requirements:
      host:
        - python
        - pip
      run:
        - nbconvert {{ version }}.*
        # the pin is handled by the run_constrained in core
        - pyppeteer
    test:
      requires:
        - pip
      commands:
        - python -m pip check
    about:
      description: nbconvert with extra packages for browser-based PDF generation

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Converting Jupyter Notebooks
  description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other
    formats via Jinja templates. The nbconvert tool allows you to convert an
    .ipynb notebook file into various static formats.
  doc_url: https://nbconvert.readthedocs.org
  dev_url: https://github.com/jupyter/nbconvert

extra:
  recipe-maintainers:
    - jakirkham
    - mpacer
    - minrk
    - pelson
    - takluyver
    - mseal
    - blink1073
    - ocefpaf
    - bollwyvl
